apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: a
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: b
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: c
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: d
      protocol: TCP
      port: 25672
      targetPort: 25672
    - name: e
      protocol: TCP
      port: 4369
      targetPort: 4369
    - name: f
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: g
      protocol: TCP
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq